name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            SAUCE_USERNAME=${{ secrets.SAUCE_USERNAME }}
            SAUCE_ACCESS_KEY=${{ secrets.SAUCE_ACCESS_KEY }}
            SAUCE_REGION=${SAUCE_REGION}
            SAUCE_BUILD_TYPE=${SAUCE_BUILD_TYPE}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          push: true
          tags: |
            leyfr01/photon-demo-docker:0.0.7
      -
        name: Install saucectl
        uses: saucelabs/saucectl-run-action@v3
        with:
          saucectl-version: latest
          skip-run: true
      -
        name: Run test from CI via Hosted Test Orchestration
        run: saucectl run
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          SAUCE_REGION: ${SAUCE_REGION}
          SAUCE_BUILD_TYPE: "CI Photon"